version: '3.3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'peopaygo'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
